### ISSUE TITLE
出现sqlmap修改检测的输出

### ISSUE THREAD

**Issue by 1peixin** [honmashironeko/sqlmap-gui#5]
输出sqlmap被修改，通过修改时间来判断，无法进行执行代码，请到github下载原版本
请修复一下

**Comment by 1peixin** [comment]
![Uploading 20240710134205.png…]()

**Comment by 1peixin** [comment]
![20240710134205](https://github.com/honmashironeko/sqlmap-gui/assets/110766472/d2550b85-3314-4f0b-9b73-7838ed368a77)

**Comment by honmashironeko** [comment]
感谢您的反馈，目前已修复，请下载新版本。此外请提供一个ID，用于本项目感谢。

**Comment by 1peixin** [comment]
> 感谢您的反馈，目前已修复，请下载新版本。此外请提供一个ID，用于本项目感谢。

id：peixin
作者处理速度挺快的嘛
