### ISSUE TITLE
English version 

### ISSUE THREAD

**Issue by husam-tariq** [honmashironeko/sqlmap-gui#8]
Can you support English Language please ?

**Comment by honmashironeko** [comment]
The English version is under planning and will be updated in the future. Thank you for your support

**Comment by husam-tariq** [comment]
> The English version is under planning and will be updated in the future. Thank you for your support

Thanks for your awesome work

**Comment by honmashironeko** [comment]
A first edition has been initially updated. If you are interested, you can try it out.

**Comment by husam-tariq** [comment]
That's awesome 👌
